#!/bin/bash

#SBATCH --job-name=template
#SBATCH --ntasks-per-node=1
#SBATCH --mem=1G
#SBATCH --time=00:15:00

echo "[INFO] Pulling Python v3.9 container..."
singularity pull docker://python:3.9-bookworm

echo "[INFO] Installing pip packages"
singularity exec python_3.9-bookworm.sif pip install --user nibabel

echo "[INFO] Starting main.py..."
singularity exec python_3.9-bookworm.sif python3 main.py

